name: Dry publish binary

on:
  push:
    branches: [ master, 'release/**'  ]
  pull_request:
    branches: [ master, 'release/**'  ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: fwilhe2/setup-kotlin@main
      - run: ./sdl.main.kts
      - uses: actions/upload-artifact@v3
        with:
          path: ./tmp/*