name: Publish binary

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: fwilhe2/setup-kotlin@main
      - run: ./sdl.main.kts
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./tmp/*
          tag: ${{ github.ref }}
          overwrite: true